Umbrella\AdminBundle\Entity\Profile:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email:
            - NotBlank: ~
            - Email: ~
            # - Umbrella\AdminBundle\Validator\Constraints\ChangeEmail: ~
        password:
            - NotBlank:
                message: 'Password field should not be blank.'
            - Length:
                min: 5
                max: 255
        firstName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 255
        lastName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 255
        homePhone:
            - NotBlank: ~
            - Length:
                min: 2
                max: 255
            - Regex: 
                pattern: "/^([0-9-_() +*])+$/i"
                message: "Number must be of the characters: numbers, space, - ()"
        cellPhone:        
            - Length:
                min: 2
                max: 255
                minMessage: "Your first name must be at least {{ limit }} characters length"
                maxMessage: "Your first name cannot be longer than {{ limit }} characters length"
            - Regex: 
                pattern: "/^([0-9-_() +*])+$/i"
                message: "Number must be of the characters: numbers, space, - ()"
        altPhone:
            - Length:
                min: 2
                max: 255
                minMessage: "Your first name must be at least {{ limit }} characters length"
                maxMessage: "Your first name cannot be longer than {{ limit }} characters length"                
            - Regex: 
                pattern: "/^([0-9-_() +*])+$/i"
                message: "Number must be of the characters: numbers, space, - ()"