umbrella_security:
    resource: "@UmbrellaSecurityBundle/Resources/config/routing.yml"
    prefix:   /

umbrella_admin:
    resource: "@UmbrellaAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

umbrella_frontend:
    resource: "@UmbrellaFrontendBundle/Resources/config/routing.yml"
    prefix:   /frontend

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"

_apy_jsformvalidation:
    resource: "@APYJsFormValidationBundle/Resources/config/routing/routing.yml"