security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_USER:   IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN:  ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:    ^(/admin/.*|/login_check|/logout)
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: home
            security: true

    access_control:
        - { path: ^/admin/.*, roles: ROLE_ADMIN }
        - { path: ^/frontend.*, roles: ROLE_USER, requires_channel: http }