# Admin remake redirect on systems users
admin:
    pattern: /admin
    defaults: { _controller: UmbrellaSecurityBundle:Auth:index }

admin:
    pattern: /admin/
    defaults: { _controller: UmbrellaSecurityBundle:Auth:index }

login:
    path:   /login
    defaults:  { _controller: UmbrellaSecurityBundle:Auth:login }

login_check:
    path: /login_check

logout:
    path: /logout