parameters:
#    umbrella_security.example.class: Umbrella\SecurityBundle\Example

services:
#    umbrella_security.example:
#        class: %umbrella_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
