<?php

namespace Proxies\__CG__\Umbrella\AdminBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Profile extends \Umbrella\AdminBundle\Entity\Profile implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getProfileID()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["profileID"];
        }
        $this->__load();
        return parent::getProfileID();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setHomePhone($homePhone)
    {
        $this->__load();
        return parent::setHomePhone($homePhone);
    }

    public function getHomePhone()
    {
        $this->__load();
        return parent::getHomePhone();
    }

    public function setCellPhone($cellPhone)
    {
        $this->__load();
        return parent::setCellPhone($cellPhone);
    }

    public function getCellPhone()
    {
        $this->__load();
        return parent::getCellPhone();
    }

    public function setAltPhone($altPhone)
    {
        $this->__load();
        return parent::setAltPhone($altPhone);
    }

    public function getAltPhone()
    {
        $this->__load();
        return parent::getAltPhone();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'profileID', 'email', 'password', 'firstName', 'lastName', 'homePhone', 'cellPhone', 'altPhone');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}